server:
  port: 9001
  tomcat:
    connection-timeout: 2s
    threads:
      max: 50
      min-spare: 5
spring:
  application:
    name: catalog-service
  datasource:
    username: root
    password: password
    url: jdbc:mysql://localhost:3306/polardb_catalog
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 5
  config:
    import: "optional:configserver:"
  profiles:
    active: test-data
  cloud:
    config:
      uri: http://localhost:8888
      request-connect-timeout: 2000
      request-read-timeout: 5000
      fail-fast: true
      retry:
        max-attempts: 6
        initial-interval: 1000
        max-interval: 2000
        multiplier: 1.1
management:
  endpoints:
    web:
      exposure:
        include: refresh
