server:
  port: 8888
  tomcat:
    connection-timeout: 2s
    threads:
      max: 50
      min-spare: 5

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sarpio/cloud-native-book-store.git
          default-label: master
          clone-on-start: true
          force-pull: true
          search-paths: configuration